def middle():
    print("""
    now you're in the middle floor ...
    Here is the main villian ...
    infront of you the queen is lying down ...
    now, the villian comes ....
    you have two option ...
    press 1 for fight the villian ...
    press 2 for exit the game ...
    """)

    choice = input("> ")

    if choice == "1":
        print("great, i think you want to win the game.")
        code()

    elif choice == "2":
        print("okk, you are going to be exit the game.")
        exit(0)

    else:
        print("you didn't pick any option . please try one more time ...")
        middle()

def code():
    print("""
    if you want to kill the villian ...
    you want to enter a code to kill the villian ...
    if you want to exit the game press 1
    Here is some hint of the code ..
    :- The code is integer number ...
    :- The code is two digit number ...
    :- The code number is related to the indian Caption Virat Kohli ...
    okk now enter te code ...
    """)

    choice = input("> ")

    if choice == "18":
        print("""
        The villian is die ...
        Now it's time to kiss the queen and wake her...
        """)
        kiss()

    elif choice == "1":
        print("you're going to exit the game...")
        exit(0)

    else:
        print("oops! you enter a wrong code try one more time !!!")
        code()

def kiss():
    print("""
    you're going to kiss the queen ...
    for kiss the queen press 1 ...
    otherwise the you press 2 for exit the game ...
    but i don't think you press 2 ....
    """)

    choice = input("> ")

    if choice == "1":
        print("""
        you kiss the queen ...
        The queen is wake up ...
        now , you married the married ...
        both , live a happy life ...
        congrats , you win the game ...
        bye! bye! i hope you enjoy the game ....
        """)
        exit(0)

    elif choice == "2":
        print("you are going to be exit the game")
        exit(0)

    else:
        print("you can't press 1 please press 1 !")
        kiss()
